name: Deploy Angular site to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: RotondoConsulting
        run: npm install

      - name: Build Angular app      
        working-directory: RotondoConsulting
        run: npm run build -- --base-href=/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: master  # The branch to deploy to
          folder: docs  # Replace with your dist folder
